name: Ignition RViz CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sarath18/ros_ign:latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup colcon workspace
      id: configure
      run: |
        cd ..
        mkdir -p /home/colcon_ws/src
        cp -r ign-rviz /home/colcon_ws/src/

    - name: Build project
      id: build
      run: |
        cd /home/colcon_ws/
        . /opt/ros/foxy/setup.sh
        colcon build
    - name: Run tests
      id: test
      run: |
        cd /home/colcon_ws/
        colcon test
